## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [183]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

import pandas as pd

#Q1-1
frame = pd.DataFrame(data)

#Q1-2

print(frame[((frame["job"]== "psychologist") | (frame["job"] == "teacher")) & (frame["num_cars"] > frame["family_size"])])

#Q1-3

print(frame[(frame["family_size"] < 3) & (frame["num_cars"] > 0)])

#Q-4
numRows = frame["job"].nunique()
print(numRows)



   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [184]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
#print(fruit)
#print(weights)

In [ ]:
#Q2
df = {'Fruit: ': fruit, 'Weight: ': weights}
frame = pd.DataFrame(df)
print(frame.groupby([fruit]).mean())



        Weight: 
apple       4.00
banana      7.25
carrot      6.00


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
#Q3-1
print(course_name)
print(np.argsort(course_name))

#Q3-2
#print(course_name[course_name "P%"])
for x in range(len(course_name)):
  if course_name[x].startswith("P"):
    check = True
    if check == True:
      print(course_name[x], " starts with P")
  else:
    print(course_name[x], " does not start with P")



['Python' 'JS' 'examples' 'PHP' 'html']
[1 3 0 2 4]
Python  starts with P
JS  does not start with P
examples  does not start with P
PHP  starts with P
html  does not start with P


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
#Q4-1
originalArray = student_id
newArray = originalArray[::-1]
print("Original: ", originalArray)
print("Reversed: ", newArray)

#Q4-2
np.sort(student_id)
print("Largest 3: ", student_id[-3:])




Original:  [1023 5202 6230 1671 1682 5241 4532]
Reversed:  [4532 5241 1682 1671 6230 5202 1023]
Largest 3:  [1682 5241 4532]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

#Q5
arr = []

for x in range(0,101):
  if x % 3 == 0 or x % 5 == 0:
    arr.append(x)
    
np_array = np.array(arr)
sum = np.sum(np_array)
print("Sum of multiples of 3 or 5 below 100: ", sum)




Sum of multiples of 3 or 5 below 100:  2418


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print("Original array: \n", arr)

#Q6 -1

new_arr = arr[:, [0, 2, 1, 3]]
print("Column 1 swapped with column 2: \n", new_arr)

# Q6 - 1
new_arr = arr[[1, 0, 2], :]
print("Row 0 swapped with row 1: \n", new_arr)

Original array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Column 1 swapped with column 2: 
 [[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
Row 0 swapped with row 1: 
 [[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
